[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wen_dev_program = "4ubxrDaVYVbP5Qmqdwe43haohnBMEaSY1aCXxxDJQVS7"

[programs.devnet]
wen_dev_program = "AaGjWPSAGxmJLTpDq3ntvnRugVfde1JV1EmVEBPhynC4"

[registry]
url = "https://api.apr.dev"

[provider]

cluster = "devnet"
wallet = "/root/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"



